# Generated by Django 3.0.7 on 2020-06-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200625_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcategory',
            options={'ordering': ('-added_on',), 'verbose_name_plural': 'Shop Categories'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
