# Generated by Django 3.0.7 on 2020-07-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_productcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
